const BASE_SOURCES = [
  {name:'SUIN-Juriscol', authority:'Ministerio de Justicia / SUIN-Juriscol', type:'Normativa/Jurisprudencia', url:'https://www.suin-juriscol.gov.co/legislacion/derechoambiental.html', priority:1, geographic_scope:'Nacional', coverage:'Normativa y jurisprudencia ambiental', crawl_urls:['https://www.suin-juriscol.gov.co/legislacion/derechoambiental.html','https://www.suin-juriscol.gov.co/suinjuriscol.html'], max_pages:2},
  {name:'Ministerio de Ambiente - Normativa', authority:'Ministerio de Ambiente y Desarrollo Sostenible', type:'Normativa', url:'https://www.minambiente.gov.co/normativa/', priority:1, geographic_scope:'Nacional', coverage:'Leyes, decretos, resoluciones, autos, circulares y conceptos', require_environment:true},
  {name:'ANLA - Normas ambientales', authority:'Autoridad Nacional de Licencias Ambientales - ANLA', type:'Normativa', url:'https://www.anla.gov.co/01_anla/37-normatividad/normas-ambientales', priority:1, geographic_scope:'Nacional', coverage:'Normativa ambiental y licenciamiento', require_environment:true},
  {name:'Corte Constitucional - Relatoría', authority:'Corte Constitucional', type:'Jurisprudencia', url:'https://www.corteconstitucional.gov.co/relatoria/', priority:1, geographic_scope:'Nacional', coverage:'Sentencias y autos constitucionales'},
  {name:'Consejo de Estado', authority:'Consejo de Estado', type:'Jurisprudencia', url:'https://www.consejodeestado.gov.co/', priority:1, geographic_scope:'Nacional', coverage:'Jurisprudencia contencioso-administrativa'},

  {name:'Ministerio de Ambiente - Políticas Públicas Ambientales', authority:'Ministerio de Ambiente y Desarrollo Sostenible', type:'Políticas', url:'https://www.minambiente.gov.co/planeacion-y-seguimiento/politicas-publicas-ambientales/', priority:1, geographic_scope:'Nacional', coverage:'Políticas públicas ambientales nacionales', accept_planning:true},
  {name:'Ministerio de Ambiente - Planes Estratégicos', authority:'Ministerio de Ambiente y Desarrollo Sostenible', type:'Planes', url:'https://www.minambiente.gov.co/planeacion-y-seguimiento/planes-estrategicos/', priority:1, geographic_scope:'Nacional', coverage:'Planes estratégicos sectoriales e institucionales', accept_planning:true},
  {name:'Ministerio de Ambiente - Plan Estratégico Sectorial', authority:'Ministerio de Ambiente y Desarrollo Sostenible', type:'Planes', url:'https://www.minambiente.gov.co/planeacion-y-seguimiento/plan-estrategico-sectorial/', priority:1, geographic_scope:'Nacional', coverage:'Plan Estratégico Sector Ambiente y seguimiento', accept_planning:true},
  {name:'DNP - Plan Nacional de Desarrollo', authority:'Departamento Nacional de Planeación - DNP', type:'Planes/Política', url:'https://www.dnp.gov.co/plan-nacional-desarrollo/pnd-2022-2026/Paginas/default.aspx', priority:1, geographic_scope:'Nacional', coverage:'Plan Nacional de Desarrollo, bases, anexos y documentos sectoriales', accept_planning:true, crawl_urls:['https://www.dnp.gov.co/plan-nacional-desarrollo/pnd-2022-2026/Paginas/default.aspx','https://dnp.gov.co/plan-nacional-desarrollo/pnd-2022-2026/'], max_pages:2},
  {name:'DNP - Repositorio CONPES', authority:'Departamento Nacional de Planeación - DNP', type:'Políticas/CONPES', url:'https://colaboracion.dnp.gov.co/biblioteca/repositorio/lists/libro/allitems.aspx', priority:1, geographic_scope:'Nacional', coverage:'Documentos CONPES y políticas públicas', accept_planning:true, require_environment:true},
  {name:'IDEAM - Publicaciones técnicas', authority:'Instituto de Hidrología, Meteorología y Estudios Ambientales - IDEAM', type:'Técnica', url:'https://www.ideam.gov.co/sala-de-prensa/publicaciones', priority:1, geographic_scope:'Nacional', coverage:'Protocolos, metodologías, lineamientos y publicaciones técnicas ambientales', accept_technical:true},
  {name:'MinVivienda - POT', authority:'Ministerio de Vivienda, Ciudad y Territorio', type:'Ordenamiento territorial', url:'https://minvivienda.gov.co/viceministerio-de-vivienda/espacio-urbano-y-territorial/plan-ordenamiento-territorial/pot', priority:1, geographic_scope:'Nacional/Municipal', coverage:'Marco, etapas y herramientas para POT/PBOT/EOT', accept_planning:true, accept_technical:true},
  {name:'MinVivienda - Herramientas POT', authority:'Ministerio de Vivienda, Ciudad y Territorio', type:'Técnica/Ordenamiento', url:'https://minvivienda.gov.co/viceministerio-de-vivienda/espacio-urbano-y-territorial/plan-ordenamiento-territorial/pot/herramientas-descargables', priority:1, geographic_scope:'Nacional/Municipal', coverage:'Guías, listas de chequeo, anexos y herramientas técnicas POT', accept_technical:true, accept_planning:true},
  {name:'IGAC - Colombia OT', authority:'Instituto Geográfico Agustín Codazzi - IGAC', type:'Ordenamiento territorial', url:'https://www.colombiaot.gov.co/', priority:1, geographic_scope:'Nacional/Municipal', coverage:'POT municipales, cartografía, normatividad y recursos de ordenamiento territorial', accept_planning:true, accept_technical:true},
  {name:'DNP - Portal Territorial', authority:'Departamento Nacional de Planeación - DNP', type:'Planeación territorial/Técnica', url:'https://portalterritorial.dnp.gov.co/Paginas/PT_HerramientasTerritoriales.aspx', priority:1, geographic_scope:'Nacional/Departamental/Municipal', coverage:'Herramientas, metodologías y lineamientos para planes de desarrollo y gestión territorial', accept_planning:true, accept_technical:true, require_environment:true},
  {name:'Parques Nacionales - Planes de Manejo', authority:'Parques Nacionales Naturales de Colombia', type:'Planes de manejo', url:'https://www.parquesnacionales.gov.co/entidad/planes-de-manejo-areas-del-spnn/', priority:1, geographic_scope:'Nacional/Regional', coverage:'Planes de manejo de áreas protegidas del Sistema de Parques Nacionales', accept_planning:true},
  {name:'Parques Nacionales - Marco normativo', authority:'Parques Nacionales Naturales de Colombia', type:'Normativa/Planes', url:'https://www.parquesnacionales.gov.co/marco-normativo-de-las-areas-protegidas/', priority:1, geographic_scope:'Nacional/Regional', coverage:'Actos administrativos, adopción de planes de manejo y fechas de publicación'},
  {name:'Parques Nacionales - Lineamientos de ordenamiento', authority:'Parques Nacionales Naturales de Colombia', type:'Técnica/Ordenamiento', url:'https://www.parquesnacionales.gov.co/lineamientos-para-integracion-areas-protegidas-al-ordenamiento-territorial/', priority:1, geographic_scope:'Nacional/Departamental/Municipal', coverage:'Guías y lineamientos para integrar áreas protegidas en ordenamiento territorial', accept_technical:true, accept_planning:true},
  {name:'UNGRD - Plan Nacional de Gestión del Riesgo', authority:'Unidad Nacional para la Gestión del Riesgo de Desastres - UNGRD', type:'Plan nacional/Técnica', url:'https://portal.gestiondelriesgo.gov.co/paginas/plan-nacional-gestion-riesgo-de-desastres.aspx', priority:1, geographic_scope:'Nacional/Departamental/Municipal', coverage:'PNGRD, adaptación al cambio climático, seguimiento, anexos y documentos técnicos', accept_planning:true, accept_technical:true},

  {name:'Gobernación de Antioquia - Plan de Desarrollo', authority:'Gobernación de Antioquia', type:'Plan departamental', url:'https://www.antioquia.gov.co/gobernacion/plan-desarrollo-2024-2027', priority:1, geographic_scope:'Departamental', department:'Antioquia', coverage:'Plan de Desarrollo Departamental y anexos', accept_planning:true},
  {name:'Gobernación de Antioquia - Ambiente y sostenibilidad', authority:'Gobernación de Antioquia', type:'Política/Planes', url:'https://www.antioquia.gov.co/index.php/informacion-de-proyectos-secretaria-de-ambiente-y-sostenibilidad', priority:1, geographic_scope:'Departamental', department:'Antioquia', coverage:'PICCA, crecimiento verde, biodiversidad, cambio climático y proyectos ambientales', accept_planning:true},
  {name:'Gobernación de Antioquia - Ordenanzas', authority:'Gobernación de Antioquia / Asamblea Departamental', type:'Normativa departamental', url:'https://www.antioquia.gov.co/index.php/component/content/category/normativa/ordenanzas', priority:1, geographic_scope:'Departamental', department:'Antioquia', coverage:'Ordenanzas y adopción de políticas y planes departamentales', require_environment:true},
  {name:'Alcaldía de Medellín - SIGAM y Plan Ambiental', authority:'Distrito de Medellín - Secretaría de Medio Ambiente', type:'Política/Plan municipal', url:'https://www.medellin.gov.co/es/secretaria-medio-ambiente/sistema-de-gestion-ambiental-de-medellin/', priority:1, geographic_scope:'Municipal', department:'Antioquia', municipality:'Medellín', coverage:'Política Ambiental de Medellín, PAM y SIGAM', accept_planning:true},
  {name:'Alcaldía de Medellín - Planes estratégicos', authority:'Distrito de Medellín', type:'Planes municipales', url:'https://www.medellin.gov.co/es/centro-documental/planes-estrategicos-y-misionales-del-distrito-especial-medellin/', priority:1, geographic_scope:'Municipal', department:'Antioquia', municipality:'Medellín', coverage:'PGIRS y planes estratégicos/misionales municipales', accept_planning:true, require_environment:true},
  {name:'Alcaldía de Medellín - Acción Climática', authority:'Distrito de Medellín - Secretaría de Medio Ambiente', type:'Plan climático', url:'https://www.medellin.gov.co/es/secretaria-medio-ambiente/cambio-climatico/', priority:1, geographic_scope:'Municipal', department:'Antioquia', municipality:'Medellín', coverage:'Plan de Acción Climática Medellín 2020-2050', accept_planning:true},
  {name:'AMVA - Plan de Gestión', authority:'Área Metropolitana del Valle de Aburrá', type:'Plan metropolitano', url:'https://www.metropol.gov.co/area/Paginas/Planeacion-estrategica/Plan-de-gestion.aspx', priority:1, geographic_scope:'Metropolitano', department:'Antioquia', coverage:'Plan de Gestión, cambio climático, río, economía circular y resiliencia territorial', accept_planning:true},
  {name:'CORNARE - PGAR', authority:'CORNARE', type:'Plan ambiental regional', url:'https://www.cornare.gov.co/plan-de-gestion-ambiental-regional/', priority:1, geographic_scope:'Regional', department:'Antioquia', coverage:'Plan de Gestión Ambiental Regional', accept_planning:true},
  {name:'CORNARE - POMCA', authority:'CORNARE', type:'Planes de cuenca', url:'https://www.cornare.gov.co/planes-de-ordenacion-y-manejo-de-cuencas-hidrograficas-pomcas/', priority:1, geographic_scope:'Regional/Municipal', department:'Antioquia', coverage:'Planes de Ordenación y Manejo de Cuencas Hidrográficas', accept_planning:true},
  {name:'CORNARE - Referentes Ambientales Municipales', authority:'CORNARE', type:'Planeación municipal', url:'https://www.cornare.gov.co/referentes-ambientales/', priority:1, geographic_scope:'Regional/Municipal', department:'Antioquia', coverage:'Referentes ambientales para planes de desarrollo municipales', accept_planning:true, accept_technical:true},
  {name:'CORANTIOQUIA - PGAR', authority:'CORANTIOQUIA', type:'Plan ambiental regional', url:'https://www.corantioquia.gov.co/plan-de-gestion-ambiental-regional-pgar/', priority:1, geographic_scope:'Regional', department:'Antioquia', coverage:'Plan de Gestión Ambiental Regional y seguimiento', accept_planning:true},
  {name:'CVC - PGAR', authority:'Corporación Autónoma Regional del Valle del Cauca - CVC', type:'Plan ambiental regional', url:'https://www.cvc.gov.co/documentos/planes-y-programas/planes/planes-de-gestion-ambiental-regional-pgar-2015-2036', priority:1, geographic_scope:'Regional', department:'Valle del Cauca', coverage:'PGAR, seguimiento y documentos descargables', accept_planning:true},
];

const REGIONAL_AUTHORITIES = [
  ['CAR - Cundinamarca','CAR','https://www.car.gov.co/','Cundinamarca'],['CARDER - Risaralda','CAR','https://www.carder.gov.co/','Risaralda'],
  ['CARDIQUE - Canal del Dique','CAR','https://cardique.gov.co/','Bolívar'],['CARSUCRE - Sucre','CAR','https://carsucre.gov.co/','Sucre'],
  ['CAS - Santander','CAR','https://cas.gov.co/','Santander'],['CDA - Norte y Oriente Amazónico','Desarrollo sostenible','https://cda.gov.co/','Amazonas/Guainía/Vaupés'],
  ['CDMB - Defensa de la Meseta de Bucaramanga','CAR','https://www.cdmb.gov.co/','Santander'],['CODECHOCÓ - Chocó','Desarrollo sostenible','https://codechoco.gov.co/','Chocó'],
  ['CORALINA - San Andrés','Desarrollo sostenible','https://www.coralina.gov.co/','San Andrés'],['CORANTIOQUIA - Centro de Antioquia','CAR','https://www.corantioquia.gov.co/','Antioquia'],
  ['CORMACARENA - Área de Manejo Especial La Macarena','Desarrollo sostenible','https://www.cormacarena.gov.co/','Meta'],['CORNARE - Ríos Negro y Nare','CAR','https://www.cornare.gov.co/','Antioquia'],
  ['CORPAMAG - Magdalena','CAR','https://www.corpamag.gov.co/','Magdalena'],['CORPOAMAZONIA - Sur de la Amazonia','Desarrollo sostenible','https://www.corpoamazonia.gov.co/','Amazonas/Caquetá/Putumayo'],
  ['CORPOBOYACÁ - Boyacá','CAR','https://www.corpoboyaca.gov.co/','Boyacá'],['CORPOCALDAS - Caldas','CAR','https://www.corpocaldas.gov.co/','Caldas'],
  ['CORPOCESAR - Cesar','CAR','https://www.corpocesar.gov.co/','Cesar'],['CORPOCHIVOR - Chivor','CAR','https://www.corpochivor.gov.co/','Boyacá'],
  ['CORPOGUAJIRA - La Guajira','CAR','https://corpoguajira.gov.co/','La Guajira'],['CORPOGUAVIO - Guavio','CAR','https://www.corpoguavio.gov.co/','Cundinamarca'],
  ['CORPONARIÑO - Nariño','CAR','https://corponarino.gov.co/','Nariño'],['CORPONOR - Norte de Santander','CAR','https://www.corponor.gov.co/','Norte de Santander'],
  ['CORPORINOQUIA - Orinoquia','CAR','https://www.corporinoquia.gov.co/','Orinoquía'],['CORPOURABÁ - Urabá','Desarrollo sostenible','https://corpouraba.gov.co/','Antioquia'],
  ['CORTOLIMA - Tolima','CAR','https://cortolima.gov.co/','Tolima'],['CVC - Valle del Cauca','CAR','https://www.cvc.gov.co/','Valle del Cauca'],
  ['CRC - Cauca','CAR','https://www.crc.gov.co/','Cauca'],['CRQ - Quindío','CAR','https://www.crq.gov.co/','Quindío'],['CSB - Sur de Bolívar','CAR','https://www.carcsb.gov.co/','Bolívar'],
  ['CVS - Valles del Sinú y San Jorge','CAR','https://www.cvs.gov.co/','Córdoba'],['CAM - Alto Magdalena','CAR','https://cam.gov.co/','Huila'],
  ['CRA - Atlántico','CAR','https://www.crautonoma.gov.co/','Atlántico'],['CORMAGDALENA - Río Grande de la Magdalena','Corporación regional','https://www.cormagdalena.gov.co/','Cuenca Magdalena'],
  ['CORPOMOJANA - Mojana y San Jorge','Desarrollo sostenible','https://corpomojana.gov.co/','Sucre/Bolívar/Córdoba'],
  ['Área Metropolitana del Valle de Aburrá','Autoridad urbana','https://www.metropol.gov.co/','Antioquia'],
  ['Secretaría Distrital de Ambiente de Bogotá','Autoridad urbana','https://ambientebogota.gov.co/','Bogotá D.C.'],
  ['DAGMA - Cali','Autoridad urbana','https://www.cali.gov.co/dagma/','Valle del Cauca']
].map(([name,type,url,department]) => ({name,authority:name,type,url,priority:2,geographic_scope:'Regional/Local',department,coverage:'Normativa, actos administrativos e instrumentos ambientales territoriales', require_environment:true}));

const SECTOR_SOURCES = [
  {name:'ANDI',authority:'ANDI - Asociación Nacional de Empresarios de Colombia',type:'Gremio / Noticias',url:'https://www.andi.com.co/Home/Noticias',priority:3,geographic_scope:'Nacional',coverage:'Noticias empresariales con impacto ambiental, energético, circular y de sostenibilidad',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Multisectorial'},
  {name:'FENALCO',authority:'FENALCO - Federación Nacional de Comerciantes',type:'Gremio / Noticias',url:'https://www.fenalco.com.co/blog/noticias-10',priority:3,geographic_scope:'Nacional',coverage:'Noticias empresariales sobre comercio, uso eficiente de recursos, economía circular, energía y sostenibilidad',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Comercio'},
  {name:'FENALCO - Monitoreo Regulatorio',authority:'FENALCO - Federación Nacional de Comerciantes',type:'Gremio / Monitoreo regulatorio',url:'https://www.fenalco.com.co/blog/juridico-2',priority:2,geographic_scope:'Nacional',coverage:'Alertas y proyectos normativos de interés empresarial; se filtran los asuntos ambientales y de sostenibilidad',accept_news:true,regulatory_monitoring:true,require_environment:true,source_category:'Gremio',sector:'Comercio'},
  {name:'CAMACOL',authority:'CAMACOL - Cámara Colombiana de la Construcción',type:'Gremio / Noticias',url:'https://camacol.co/prensa/noticias',priority:3,geographic_scope:'Nacional',coverage:'Noticias del sector constructor con filtro ambiental, territorial y de sostenibilidad',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Construcción'},
  {name:'CAMACOL - Sostenibilidad',authority:'CAMACOL - Cámara Colombiana de la Construcción',type:'Gremio / Sostenibilidad',url:'https://camacol.co/actualidad/publicaciones/revista-urbana/sostenibilidad',priority:2,geographic_scope:'Nacional',coverage:'Construcción sostenible, certificaciones, materiales, descarbonización y resiliencia',accept_news:true,specialist_sustainability:true,source_category:'Gremio',sector:'Construcción'},
  {name:'CECODES - Sostenibilidad empresarial',authority:'Consejo Empresarial Colombiano para el Desarrollo Sostenible - CECODES',type:'Sostenibilidad empresarial',url:'https://www.cecodes.org.co/',priority:2,geographic_scope:'Nacional',coverage:'ESG/ASG, net zero, naturaleza positiva, economía circular, DDHH y empresa, transparencia y tendencias empresariales',accept_news:true,specialist_sustainability:true,source_category:'Centro empresarial de sostenibilidad',sector:'Multisectorial'},
  {name:'CCCS - Noticias de actualidad',authority:'Consejo Colombiano de Construcción Sostenible - CCCS',type:'Sostenibilidad / Noticias',url:'https://www.cccs.org.co/noticias-actualidad/',priority:2,geographic_scope:'Nacional',coverage:'Construcción sostenible, riesgo climático, doble materialidad, certificaciones, ciudades y biodiversidad',accept_news:true,specialist_sustainability:true,source_category:'Consejo de sostenibilidad',sector:'Construcción e inmobiliario'},
  {name:'ANDESCO - Noticias',authority:'ANDESCO - Asociación Nacional de Empresas de Servicios Públicos y Comunicaciones',type:'Gremio / Noticias',url:'https://andesco.org.co/noticias/',priority:2,geographic_scope:'Nacional',coverage:'Agua, saneamiento, residuos, energía, regulación, eficiencia y sostenibilidad de servicios públicos',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Servicios públicos'},
  {name:'ANDESCO - Comunicados',authority:'ANDESCO - Asociación Nacional de Empresas de Servicios Públicos y Comunicaciones',type:'Gremio / Comunicados',url:'https://congreso.andesco.org.co/category/comunicados/',priority:3,geographic_scope:'Nacional',coverage:'Comunicados sectoriales de agua, aseo, energía, regulación y sostenibilidad',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Servicios públicos'},
  {name:'ACP - Hechos de Sostenibilidad',authority:'Asociación Colombiana del Petróleo y Gas - ACP',type:'Gremio / Sostenibilidad',url:'https://acp.com.co/portal/categoria/hechos-de-sostenibilidad/',priority:2,geographic_scope:'Nacional',coverage:'Hechos empresariales de sostenibilidad, agua, energía, movilidad, biodiversidad y gestión social del sector hidrocarburos',accept_news:true,specialist_sustainability:true,source_category:'Gremio',sector:'Hidrocarburos'},
  {name:'ACP - Sala de Prensa',authority:'Asociación Colombiana del Petróleo y Gas - ACP',type:'Gremio / Noticias',url:'https://acp.com.co/portal/categoria/sala-de-prensa/',priority:3,geographic_scope:'Nacional',coverage:'Política pública, seguridad energética, regulación y asuntos ambientales del sector hidrocarburos',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Hidrocarburos'},
  {name:'Naturgas - Comunicados',authority:'Asociación Colombiana de Gas Natural - Naturgas',type:'Gremio / Noticias',url:'https://naturgas.com.co/category/comunicados/',priority:3,geographic_scope:'Nacional',coverage:'Seguridad energética, gas natural, hidrógeno, gases renovables, regulación y sostenibilidad',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Gas natural y energía'},
  {name:'SER Colombia - Estudios y documentos',authority:'Asociación de Energías Renovables Colombia - SER Colombia',type:'Gremio / Estudios',url:'https://ser-colombia.org/estudios-y-documentos/',priority:2,geographic_scope:'Nacional',coverage:'Energías renovables, transición energética, estudios ambientales, regulación y proyectos FNCER',accept_news:true,accept_technical:true,specialist_sustainability:true,source_category:'Gremio',sector:'Energías renovables'},
  {name:'ACM - Actualidad',authority:'Asociación Colombiana de Minería - ACM',type:'Gremio / Noticias',url:'https://acmineria.com.co/actualidad/',priority:3,geographic_scope:'Nacional',coverage:'Minería responsable, regulación, energía, biodiversidad, territorio y sostenibilidad del sector minero',accept_news:true,require_business_environment:true,source_category:'Gremio',sector:'Minería'},
  {name:'Acoplásticos - Publicaciones',authority:'Acoplásticos',type:'Gremio / Publicaciones',url:'https://acoplasticos.org/publicaciones/',priority:2,geographic_scope:'Nacional',coverage:'Economía circular, plásticos, reciclaje, ecodiseño, regulación e innovación sostenible',accept_news:true,accept_technical:true,specialist_sustainability:true,source_category:'Gremio',sector:'Plásticos, reciclaje, pinturas y caucho'},
  {name:'Fedepalma - Sostenibilidad Ambiental',authority:'Fedepalma',type:'Gremio / Sostenibilidad',url:'https://fedepalma.org/sostenibilidad-ambiental/',priority:3,geographic_scope:'Nacional',coverage:'Gestión ambiental y sostenibilidad del sector palmero, biodiversidad, agua, clima y producción sostenible',accept_news:true,specialist_sustainability:true,source_category:'Gremio',sector:'Agroindustria palmera'},
  {name:'Asocaña - Publicaciones',authority:'Asocaña - Sector Agroindustrial de la Caña',type:'Gremio / Publicaciones',url:'https://www.asocana.org/modules/documentos/default.aspx',priority:3,geographic_scope:'Nacional/Regional',department:'Valle del Cauca/Cauca',coverage:'Informes de sostenibilidad, ambiente, energía, agua y desempeño del sector agroindustrial de la caña',accept_news:true,accept_technical:true,require_business_environment:true,source_category:'Gremio',sector:'Agroindustria de la caña'},
  {name:'ASOCARS',authority:'ASOCARS - Asociación de Corporaciones Autónomas Regionales',type:'Gremial/sectorial',url:'https://www.asocars.org.co/',priority:3,geographic_scope:'Nacional/Regional',coverage:'Noticias y análisis del sistema de CAR, política ambiental y gestión regional',accept_news:true,require_environment:true,source_category:'Asociación de autoridades ambientales',sector:'Gestión ambiental pública'},

  {name:'Sustenomics',authority:'Sustenomics',type:'Portal especializado / Sostenibilidad',url:'https://sustenomics.com/',priority:4,geographic_scope:'Colombia/Latinoamérica',coverage:'Sostenibilidad empresarial, economía circular, ESG/ASG, clima, innovación y análisis corporativo',accept_news:true,specialist_sustainability:true,source_category:'Portal especializado',sector:'Multisectorial'},
  {name:'Comunicación Sostenible',authority:'Comunicación Sostenible',type:'Portal especializado / Sostenibilidad',url:'https://comunicacionsostenible.co/',priority:4,geographic_scope:'Colombia/Latinoamérica',coverage:'Noticias, casos empresariales, economía circular, cambio climático y sostenibilidad',accept_news:true,specialist_sustainability:true,source_category:'Portal especializado',sector:'Multisectorial'},
  {name:'El Espectador - Ambiente',authority:'El Espectador - Redacción Ambiente',type:'Medio / Ambiente',url:'https://www.elespectador.com/ambiente/',priority:4,geographic_scope:'Colombia',coverage:'Noticias ambientales de Colombia: agua, biodiversidad, clima, política ambiental, bosques, minería y territorio',accept_news:true,specialist_environment:true,source_category:'Medio especializado',sector:'Ambiental general'},
  {name:'Mongabay Latam - Colombia',authority:'Mongabay Latam',type:'Portal ambiental',url:'https://es.mongabay.com/list/colombia/',priority:4,geographic_scope:'Colombia',coverage:'Periodismo ambiental sobre biodiversidad, bosques, deforestación, minería, clima, comunidades y conservación',accept_news:true,specialist_environment:true,source_category:'Portal ambiental',sector:'Ambiental general'}
];

const CATALOG = [...BASE_SOURCES, ...REGIONAL_AUTHORITIES, ...SECTOR_SOURCES];
const BY_NAME = new Map(CATALOG.map(s => [s.name, s]));

function enrich(source) {
  const c = BY_NAME.get(source.name) || {};
  return {
    ...source,
    ...c,
    crawl_urls: c.crawl_urls || [c.url || source.url].filter(Boolean),
    max_pages: c.max_pages || 1,
    authority: c.authority || source.authority || source.name,
    geographic_scope: c.geographic_scope || source.geographic_scope || 'Colombia',
    department: c.department || source.department || null,
    municipality: c.municipality || source.municipality || null,
    coverage: c.coverage || source.coverage || null,
    accept_planning: !!c.accept_planning,
    accept_technical: !!c.accept_technical,
    accept_news: !!c.accept_news,
    regulatory_monitoring: !!c.regulatory_monitoring,
    require_environment: !!c.require_environment,
    require_business_environment: !!c.require_business_environment,
    specialist_sustainability: !!c.specialist_sustainability,
    specialist_environment: !!c.specialist_environment,
    source_category: c.source_category || source.source_category || 'Fuente institucional',
    sector: c.sector || source.sector || null
  };
}

module.exports = { CATALOG, enrich };
